# Generated by Django 4.2.30 on 2026-05-17 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_blogs', models.PositiveIntegerField(default=0)),
                ('new_comments', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'site_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('blog_create', 'Blog Created'), ('blog_edit', 'Blog Edited'), ('blog_delete', 'Blog Deleted'), ('blog_approve', 'Blog Approved'), ('blog_reject', 'Blog Rejected'), ('comment_add', 'Comment Added'), ('profile_edit', 'Profile Edited')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx')],
            },
        ),
    ]
