# Generated by Django 4.2.30 on 2026-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('blog_submitted', 'Blog Submitted'), ('blog_approved', 'Blog Approved'), ('blog_rejected', 'Blog Rejected'), ('comment', 'New Comment'), ('reply', 'Comment Reply'), ('like', 'Blog Liked'), ('comment_like', 'Comment Liked'), ('system', 'System Notification')], max_length=30),
        ),
    ]
